-

diff --git a/usr/lib/enigma2/python/Plugins/Extensions/Manager/auto b/usr/lib/enigma2/python/Plugins/Extensions/Manager/auto
--- a/usr/lib/enigma2/python/Plugins/Extensions/Manager/auto
+++ b/usr/lib/enigma2/python/Plugins/Extensions/Manager/auto
@@ -14,7 +14,7 @@ echo ""
 echo ""
 echo "Downloading ${softcam}"
 ## wget ${softcam} -O /etc/tuxbox/config/SoftCam.Key || echo "Error: Couldn't connect to ${softcam}"
-wget ${softcam} -O /usr/keys/SoftCam.Key || echo "Error: Couldn't connect to ${softcam}"
+wget --no-check-certificate -U 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36' -P '/usr/keys/' ${softcam} || echo "Error: Couldn't connect to ${softcam}"
 echo ""
 echo ""
 echo "* Installed Successfully *"
@@ -26,3 +26,5 @@ KeyDate=`/bin/date -r /usr/keys/SoftCam.Key +%d.%m.%y-%H:%M:%S`
 exit 0
 
 ## wget https://raw.githubusercontent.com/MOHAMED19OS/SoftCam_Emu/main/SoftCam.Key -O /usr/keys/SoftCam.Key																											 
+
+## wget --no-check-certificate -U 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36' -P '/usr/keys/SoftCam.Key' ${softcam}
